# Generated by Django 4.2 on 2023-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
